name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        python app.py &
        sleep 5

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Deploy only when code is in main branch
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: devops-prasanth-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Run basic test
      run: |
        python app.py &
        sleep 5

    - name: Build Docker Image (optional)
      run: docker build -t myapp .
